services:
  # Your Python UI & Control Logic
  gg:
    build: .
    container_name: gouda-gaze
    restart: unless-stopped
    volumes:
      - .:/gouda-gaze
      - ./logs:/gouda-gaze/logs  # Persist logs on host
    network_mode: host
    environment:
      - PI_IP_TS=${PI_IP_TS}
      - CAM_IP=${CAM_IP}
      - CAM_USER=${CAM_USER}
      - CAM_PASS=${CAM_PASS}
      - CAM_CHANNEL=${CAM_CHANNEL}
      - PTZ_SPEED=${PTZ_SPEED}
      - PTZ_DURATION=${PTZ_DURATION}

  # Real-Time Video Engine (WebRTC)
  streamer:
    image: alexxit/go2rtc
    container_name: gouda-streamer
    network_mode: host
    restart: unless-stopped
    environment:
      - CAM_IP=${CAM_IP}
      - CAM_USER=${CAM_USER}
      - CAM_PASS=${CAM_PASS}
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml